### PR TITLE
Complete LAPACK bindings

### PR DESCRIPTION
**Pull request by cmr**

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Gosh, you are quick! Thanks for the effort!

You’ve removed the dependency on `libblas-sys`, and now this package is no longer self-contained: `libblas` (previously provided by `libblas-sys`) is still needed for the linker to succeed. In order to demonstrate this, I’ve created a test. Please have a look.

`#[link(name = "gfortran")]` is actually also needed. It might be optional if you’re compiling on a Linux machine, but it’s mandatory on a Mac.

Lastly, I’m curious what is the motivation behind making `trans`, `uplo`, and such be `*mut c_char` instead of `*const c_char`? Do you want to follow the way it is defined in [the C version][1]? I have no problem with that.

Thanks again!

[1]: http://www.netlib.org/clapack/clapack.h

**Comment by cmr** [comment]
Yeah, I used `*mut c_char` to match the C header. Fixing the other issues...

**Comment by cmr** [comment]
With the new provider architecture, this should be good.

**Comment by IvanUkhov** [comment]
@cmr, thanks! In order to be able to publish the packages (`libblas-sys` and `liblapack-sys`) on crates.io, all dependencies should come from the same source. In other words, you need to publish your providers on crates.io.

**Comment by cmr** [comment]
There's some sort of bug with cargo preventing me from uploading `openblas-blas-provider` (it always gives "http error: Timeout was reached"), but the netlib provider is published.

**Pull request merged**
